#define OSUSE_LIBRARY		TRUE
#define OSLIBRARY_TYPE		OSF
#define OSLIBRARY_GLOBALS	OSF
#define OSLIBRARY_CONFIG	OSA
#define OSEVENTS			3
#define OSEVENTS_FLAGS		0
#define OSMESSAGE_QUEUES	0
#define OSTASKS				3